# --------------------------------------------------------------------------------------
# as_json method for Fixture Rails Model - simply remove the attributes
# you do not want to send over the wire - send via render :text => object.to_json
# generated by XcodeTemplate helper (c) jTribe Holdings Pty Ltd 2011 - www.jtribe.com.au
# --------------------------------------------------------------------------------------

def as_json
  h = Hash.new
  h[:awayteam] = self.awayteam if !self.awayteam.nil?
  h[:content] = self.content if !self.content.nil?
  h[:created_at] = self.created_at.strftime('%Y-%m-%d %H:%M:%S') if !self.created_at.nil?
  h[:game_id] = self.game_id if !self.game_id.nil?
  h[:hometeam] = self.hometeam if !self.hometeam.nil?
  h[:fixture_id] = self.fixture_id if !self.fixture_id.nil?
  h[:matchdate] = self.matchdate.strftime('%Y-%m-%d %H:%M:%S') if !self.matchdate.nil?
  h[:updated_at] = self.updated_at.strftime('%Y-%m-%d %H:%M:%S') if !self.updated_at.nil?
  return h
end

