// --------------------------------------------------------------------------------------
// Fixture - ObjC Model Declaration based on Ruby on Rails model
// generated by XcodeTemplate helper (c) jTribe Holdings Pty Ltd 2011 - www.jtribe.com.au
// --------------------------------------------------------------------------------------

#import <Foundation/Foundation.h>

@interface Fixture : NSObject {
   NSString     *_awayteam;
   NSString     *_content;
   NSDate       *_created_at;
   NSInteger    game_id;
   NSString     *_hometeam;
   NSInteger    fixture_id;
   NSDate       *_matchdate;
   NSDate       *_updated_at;
}

-(id)initWithDictionary:(NSDictionary *)dictionary;


@property (nonatomic,retain)   NSString     *awayteam;
@property (nonatomic,retain)   NSString     *content;
@property (nonatomic,retain)   NSDate       *created_at;
@property (assign)             NSInteger    game_id;
@property (nonatomic,retain)   NSString     *hometeam;
@property (assign)             NSInteger    fixture_id;
@property (nonatomic,retain)   NSDate       *matchdate;
@property (nonatomic,retain)   NSDate       *updated_at;

@end
