require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PredictsController do

  # This should return the minimal set of attributes required to create a valid
  # Predict. As you add validations to Predict, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PredictsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all predicts as @predicts" do
      predict = Predict.create! valid_attributes
      get :index, {}, valid_session
      assigns(:predicts).should eq([predict])
    end
  end

  describe "GET show" do
    it "assigns the requested predict as @predict" do
      predict = Predict.create! valid_attributes
      get :show, {:id => predict.to_param}, valid_session
      assigns(:predict).should eq(predict)
    end
  end

  describe "GET new" do
    it "assigns a new predict as @predict" do
      get :new, {}, valid_session
      assigns(:predict).should be_a_new(Predict)
    end
  end

  describe "GET edit" do
    it "assigns the requested predict as @predict" do
      predict = Predict.create! valid_attributes
      get :edit, {:id => predict.to_param}, valid_session
      assigns(:predict).should eq(predict)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Predict" do
        expect {
          post :create, {:predict => valid_attributes}, valid_session
        }.to change(Predict, :count).by(1)
      end

      it "assigns a newly created predict as @predict" do
        post :create, {:predict => valid_attributes}, valid_session
        assigns(:predict).should be_a(Predict)
        assigns(:predict).should be_persisted
      end

      it "redirects to the created predict" do
        post :create, {:predict => valid_attributes}, valid_session
        response.should redirect_to(Predict.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved predict as @predict" do
        # Trigger the behavior that occurs when invalid params are submitted
        Predict.any_instance.stub(:save).and_return(false)
        post :create, {:predict => {}}, valid_session
        assigns(:predict).should be_a_new(Predict)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Predict.any_instance.stub(:save).and_return(false)
        post :create, {:predict => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested predict" do
        predict = Predict.create! valid_attributes
        # Assuming there are no other predicts in the database, this
        # specifies that the Predict created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Predict.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => predict.to_param, :predict => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested predict as @predict" do
        predict = Predict.create! valid_attributes
        put :update, {:id => predict.to_param, :predict => valid_attributes}, valid_session
        assigns(:predict).should eq(predict)
      end

      it "redirects to the predict" do
        predict = Predict.create! valid_attributes
        put :update, {:id => predict.to_param, :predict => valid_attributes}, valid_session
        response.should redirect_to(predict)
      end
    end

    describe "with invalid params" do
      it "assigns the predict as @predict" do
        predict = Predict.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Predict.any_instance.stub(:save).and_return(false)
        put :update, {:id => predict.to_param, :predict => {}}, valid_session
        assigns(:predict).should eq(predict)
      end

      it "re-renders the 'edit' template" do
        predict = Predict.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Predict.any_instance.stub(:save).and_return(false)
        put :update, {:id => predict.to_param, :predict => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested predict" do
      predict = Predict.create! valid_attributes
      expect {
        delete :destroy, {:id => predict.to_param}, valid_session
      }.to change(Predict, :count).by(-1)
    end

    it "redirects to the predicts list" do
      predict = Predict.create! valid_attributes
      delete :destroy, {:id => predict.to_param}, valid_session
      response.should redirect_to(predicts_url)
    end
  end

end
